docker-compose-yaml: docker-compose.yml
x-trusted-ips: &trusted-ips |
  set_real_ip_from 23.235.32.0/20;
  set_real_ip_from 43.249.72.0/22;
  set_real_ip_from 103.244.50.0/24;
  set_real_ip_from 103.245.222.0/23;
  set_real_ip_from 103.245.224.0/24;
  set_real_ip_from 104.156.80.0/20;
  set_real_ip_from 140.248.64.0/18;
  set_real_ip_from 140.248.128.0/17;
  set_real_ip_from 146.75.0.0/17;
  set_real_ip_from 151.101.0.0/16;
  set_real_ip_from 157.52.64.0/18;
  set_real_ip_from 167.82.0.0/17;
  set_real_ip_from 167.82.128.0/20;
  set_real_ip_from 167.82.160.0/20;
  set_real_ip_from 167.82.224.0/20;
  set_real_ip_from 172.111.64.0/18;
  set_real_ip_from 185.31.16.0/22;
  set_real_ip_from 199.27.72.0/21;
  set_real_ip_from 199.232.0.0/16;
  set_real_ip_from 2a04:4e40::/32;
  set_real_ip_from 2a04:4e42::/32;
  add_header X-Lagoon-Testing "testing" always;

environments:
  main:
    routes:
      - nginx:
        - "testing-bare.fastlytraefik.test6.amazee.io":
        - "testing-realip.fastlytraefik.test6.amazee.io":
            annotations:
              nginx.ingress.kubernetes.io/server-snippet: *trusted-ips
              nginx.ingress.kubernetes.io/cors-allow-origin: https://testing-realip-somethingelse.fastlytraefik.test6.amazee.io
              nginx.ingress.kubernetes.io/enable-cors: 'true'
              nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
              nginx.ingress.kubernetes.io/cors-allow-headers: X-CustomHeader, Keep-Alive, User-Agent, Cache-Control, Content-Type, Authorization
              nginx.ingress.kubernetes.io/cors-allow-methods: GET, PUT, POST, DELETE, PATCH, OPTIONS

